Restaurant Model
Ksquare-University/rc-api pull request #11
Opened 2022-12-30 14:24 UTC by YumilRuedaFlores-Ksquare

2022-12-30 23:16 UTC, ArgenisGonzalez-Ksquare approved these changes

2023-01-03 18:42 UTC, ClaudiaDiaz-Ksquare reviewed
Is the "await Model.sync();" at the end of each model file necessary?

2023-01-03 20:56 UTC, ArgenisGonzalez-Ksquare approved these changes

2023-01-03 21:08 UTC, GabrielOsorno-Ksquare commented on src/models/Restaurant.model.ts
> +    sequelize // Instance of sequelize that reflects the connection
I think we should all add tableName, so all the table names are standardized at snake_case

2023-01-03 21:16 UTC, ArgenisGonzalez-Ksquare submitted a review, later dismissed

2023-01-03 22:08 UTC, ClaudiaDiaz-Ksquare requested changes

2023-01-03 22:08 UTC, ClaudiaDiaz-Ksquare commented on src/routes/Restaurant.routes.ts
> +router.post("/:id",controller.updateRestaurantById);
There are 2 post endpoints to the same route /:id, but they use different controllers, one is for deleting and one for updating apparently. Can you verify which one stays or which one should change of route or endpoint?

2023-01-04 01:33 UTC, GabrielOsorno-Ksquare commented on src/models/Restaurant.model.ts
> +    sequelize // Instance of sequelize that reflects the connection
Would be great if you change it to 'restaurant' C;, same, just for consistency

2023-01-04 16:40 UTC, ClaudiaDiaz-Ksquare submitted a review, later dismissed
Thanks

2023-01-04 16:42 UTC, GabrielOsorno-Ksquare commented on src/models/Restaurant.model.ts
> +        }
You should use allowNull: false on the props that can never be null.

2023-01-04 16:50 UTC, ClaudiaDiaz-Ksquare approved these changes
Thanks

2023-01-04 16:50 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-05 17:10 UTC, MarianaLopez-Ksquare submitted a review, later dismissed

2023-01-05 20:15 UTC, GenaroArredondo-Ksquare approved these changes

2023-01-05 20:15 UTC, RodrigoLeon-Ksquare approved these changes

2023-01-05 20:19 UTC, merged