Create Payment Method model
Ksquare-University/rc-api pull request #15
Opened 2022-12-30 14:42 UTC by RodrigoLeon-Ksquare

2023-01-03 18:51 UTC, BrandonHernandez-Ksquare approved these changes

2023-01-03 18:55 UTC, ClaudiaDiaz-Ksquare reviewed
did you add this model to the index file inside the models array?

2023-01-03 18:57 UTC, ClaudiaDiaz-Ksquare approved these changes

2023-01-03 19:57 UTC, GabrielOsorno-Ksquare requested changes

2023-01-03 19:57 UTC, GabrielOsorno-Ksquare commented on src/models/PaymentMethod.model.ts
> +      sequelize, // Instance of sequelize that reflects the connection
I think we should all add tableName, so all the table names are standardized at snake_case.

2023-01-03 20:48 UTC, BrandonHernandez-Ksquare submitted a review, later dismissed

2023-01-03 22:25 UTC, BrandonHernandez-Ksquare submitted a review, later dismissed

2023-01-03 22:33 UTC, BrandonHernandez-Ksquare submitted a review, later dismissed

2023-01-04 01:43 UTC, GabrielOsorno-Ksquare commented on src/models/PaymentMethod.model.ts
> +  declare id: number;
Maybe CreationOptional?

2023-01-04 01:43 UTC, GabrielOsorno-Ksquare commented on src/models/PaymentMethod.model.ts
> +  declare billingDetailsId: number;
We are using snake_case, so maybe 'billing_details_id'

2023-01-04 01:43 UTC, GabrielOsorno-Ksquare commented on src/models/PaymentMethod.model.ts
> +      billingDetailsId: DataTypes.INTEGER,
allowNull: false on the fields that can't be empty(or a defaultValue if its the case)

2023-01-04 14:19 UTC, RodrigoLeon-Ksquare commented on src/models/PaymentMethod.model.ts
> +      billingDetailsId: DataTypes.INTEGER,
Hi gabriel I did the changes

2023-01-04 15:01 UTC, GabrielOsorno-Ksquare commented on src/models/PaymentMethod.model.ts
> +        allowNull: false,
If billing_details_id is declared with CreationOptional it may be null. Maybe it shouldn't be CreationOptional?

2023-01-04 15:12 UTC, RodrigoLeon-Ksquare commented on src/models/PaymentMethod.model.ts
> +        allowNull: false,
Hi gabriel  you´re right. I eliminate the creationOptional

2023-01-04 16:30 UTC, YumilRuedaFlores-Ksquare approved these changes

2023-01-04 16:31 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-04 16:31 UTC, ClaudiaDiaz-Ksquare approved these changes

2023-01-05 21:27 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-05 21:27 UTC, GenaroArredondo-Ksquare approved these changes

2023-01-05 21:28 UTC, merged