Opening Days Module
Ksquare-University/rc-api pull request #18
Opened 2022-12-30 18:28 UTC by MarianaLopez-Ksquare

2022-12-30 23:15 UTC, ArgenisGonzalez-Ksquare submitted a review, later dismissed

2023-01-03 18:42 UTC, YumilRuedaFlores-Ksquare submitted a review, later dismissed

2023-01-03 18:50 UTC, ArgenisGonzalez-Ksquare approved these changes

2023-01-03 19:49 UTC, GabrielOsorno-Ksquare requested changes

2023-01-03 19:49 UTC, GabrielOsorno-Ksquare commented on src/models/OpeningDays.model.ts
> +    sequelize // Instance of sequelize that reflects the connection
I think we should all add tableName, so all the table names are standardized at snake_case

2023-01-03 19:49 UTC, GabrielOsorno-Ksquare commented on src/models/OpeningDays.model.ts
> +    declare id: number;
Maybe CreationOptional?

2023-01-03 19:49 UTC, GabrielOsorno-Ksquare commented on src/models/OpeningDays.model.ts
> +        }
Two primary keys?

2023-01-03 21:17 UTC, ArgenisGonzalez-Ksquare approved these changes

2023-01-04 16:34 UTC, YumilRuedaFlores-Ksquare commented on src/models/OpeningDays.model.ts
> +        },
Add is_deleted

2023-01-04 16:52 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-04 16:52 UTC, YumilRuedaFlores-Ksquare approved these changes

2023-01-05 21:56 UTC, GenaroArredondo-Ksquare approved these changes

2023-01-05 21:56 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-05 22:13 UTC, merged