Opening Times Model
Ksquare-University/rc-api pull request #19
Opened 2022-12-30 18:39 UTC by MarianaLopez-Ksquare

2022-12-30 18:48 UTC, YumilRuedaFlores-Ksquare approved these changes

2022-12-30 23:15 UTC, ArgenisGonzalez-Ksquare submitted a review, later dismissed

2023-01-03 19:20 UTC, YumilRuedaFlores-Ksquare requested changes
commit to main

2023-01-03 19:20 UTC, GabrielOsorno-Ksquare commented on src/models/OpeningTimes.model.ts
> +    declare id: number;
Maybe CreationOptional?

2023-01-03 21:17 UTC, ArgenisGonzalez-Ksquare approved these changes

2023-01-04 16:32 UTC, YumilRuedaFlores-Ksquare commented on src/models/OpeningTimes.model.ts
> +        }
add is_deleted

2023-01-04 16:43 UTC, ClaudiaDiaz-Ksquare approved these changes

2023-01-04 16:43 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-04 16:51 UTC, YumilRuedaFlores-Ksquare approved these changes

2023-01-05 22:15 UTC, YumilRuedaFlores-Ksquare approved these changes

2023-01-05 22:16 UTC, JonathanCastillo-Ksquare approved these changes

2023-01-05 22:17 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-05 22:18 UTC, merged