Task 19599
Ksquare-University/rc-api pull request #21
Opened 2022-12-30 20:01 UTC by JonathanCastillo-Ksquare

2023-01-03 18:51 UTC, ArgenisGonzalez-Ksquare submitted a review, later dismissed

2023-01-03 18:54 UTC, YumilRuedaFlores-Ksquare submitted a review, later dismissed

2023-01-03 19:12 UTC, GabrielOsorno-Ksquare requested changes

2023-01-03 19:12 UTC, GabrielOsorno-Ksquare commented on src/models/Owner.model.ts
> +    declare user_id: number;
I think user_id should be a string.

2023-01-03 21:46 UTC, JonathanCastillo-Ksquare commented on src/models/Owner.model.ts
> +    declare user_id: number;
You're right! Thank you, I will change it immediately.

2023-01-03 22:13 UTC, GabrielOsorno-Ksquare submitted a review, later dismissed

2023-01-03 22:15 UTC, YumilRuedaFlores-Ksquare reviewed
ADD dist into .gitignore

2023-01-03 22:32 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-03 22:37 UTC, YumilRuedaFlores-Ksquare approved these changes

2023-01-04 16:38 UTC, ClaudiaDiaz-Ksquare submitted a review, later dismissed

2023-01-04 16:38 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-05 23:17 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-05 23:17 UTC, GenaroArredondo-Ksquare approved these changes

2023-01-05 23:17 UTC, YumilRuedaFlores-Ksquare approved these changes

2023-01-05 23:24 UTC, merged