User model created
Ksquare-University/rc-api pull request #4
Opened 2022-12-29 15:18 UTC by ClaudiaDiaz-Ksquare

Create User model

2022-12-29 22:09 UTC, ArgenisGonzalez-Ksquare submitted a review, later dismissed

2022-12-30 13:21 UTC, GabrielOsorno-Ksquare commented on src/models/user.model.ts
> +            type: DataTypes.STRING,
I think the role should never be null, so allowNull or defaultValue could be options.

2022-12-30 15:08 UTC, GabrielOsorno-Ksquare commented on src/models/user.model.ts
> +    declare id: CreationOptional<string>;
Should id be optional?

2023-01-03 18:59 UTC, ClaudiaDiaz-Ksquare commented on src/models/user.model.ts
> +    declare id: CreationOptional<string>;
I think yes because that's how we made it in the HMS project since the id is created automatically with firebase, not directly by us

2023-01-03 19:11 UTC, GabrielOsorno-Ksquare commented on src/models/user.model.ts
> +    declare id: CreationOptional<string>;
We are not generating the IDs, but we still need to pass them when creating a new User.

2023-01-03 19:52 UTC, GabrielOsorno-Ksquare requested changes

2023-01-03 19:52 UTC, GabrielOsorno-Ksquare commented on src/models/user.model.ts
> +    sequelize
I think we should all add tableName, so all the table names are standardized at snake_case

2023-01-03 19:52 UTC, GabrielOsorno-Ksquare commented on src/models/user.model.ts
> +            type: DataTypes.STRING,
I think you missed role :p

2023-01-03 20:47 UTC, BrandonHernandez-Ksquare approved these changes

2023-01-03 22:38 UTC, BrandonHernandez-Ksquare submitted a review, later dismissed

2023-01-04 01:36 UTC, GabrielOsorno-Ksquare commented on src/models/user.model.ts
> +    sequelize
Minor thing! I think we are using table names in the singular, like 'user', just for consistency c;

2023-01-04 01:37 UTC, GabrielOsorno-Ksquare commented on src/models/user.model.ts
> +    tableName: 'users',
Minor thing! I think we are using table names in the singular, like 'user', just for consistency c;

2023-01-04 02:34 UTC, GabrielOsorno-Ksquare submitted a review, later dismissed

2023-01-04 07:31 UTC, GenaroArredondo-Ksquare approved these changes

2023-01-04 19:16 UTC, BrandonHernandez-Ksquare approved these changes

2023-01-04 20:07 UTC, GenaroArredondo-Ksquare approved these changes

2023-01-05 18:00 UTC, merged