Task 19594 19605
Ksquare-University/rc-api pull request #8
Opened 2022-12-29 22:49 UTC by BrandonHernandez-Ksquare

models client and sale done

2023-01-03 19:03 UTC, ClaudiaDiaz-Ksquare reviewed
Maybe the references could be creation optional, and did you add the models to the models array (for initialization) inside the index file?

2023-01-03 19:05 UTC, GenaroArredondo-Ksquare approved these changes

2023-01-03 19:06 UTC, ClaudiaDiaz-Ksquare approved these changes

2023-01-03 19:16 UTC, ClaudiaDiaz-Ksquare reviewed
Just add the models inside the models array in the index file, for initizalization

2023-01-03 19:17 UTC, ClaudiaDiaz-Ksquare submitted a review, later dismissed

2023-01-03 22:49 UTC, ClaudiaDiaz-Ksquare approved these changes

2023-01-03 22:49 UTC, GabrielOsorno-Ksquare requested changes

2023-01-03 22:49 UTC, GabrielOsorno-Ksquare commented on src/models/Customer.model.ts
> +    declare user_id: number;
I think id should be CreationOptional and user_id a string. status could be CreationOptional too??

2023-01-03 22:49 UTC, GabrielOsorno-Ksquare commented on src/models/Customer.model.ts
> +        }
Same, user_id to STRING, and status may have a dafaultValue. full_name could have allowNull: false

2023-01-03 22:49 UTC, GabrielOsorno-Ksquare commented on src/models/Sale.model.ts
> +
id should have CreationOptional

2023-01-03 22:49 UTC, GabrielOsorno-Ksquare commented on src/models/Sale.model.ts
> +
references should be allowNull: true I think

2023-01-03 22:53 UTC, BrandonHernandez-Ksquare commented on src/models/Customer.model.ts
> +    declare user_id: number;
why should user_id be a string?

2023-01-03 23:57 UTC, GabrielOsorno-Ksquare approved these changes

2023-01-04 08:12 UTC, GenaroArredondo-Ksquare approved these changes

2023-01-05 18:52 UTC, ClaudiaDiaz-Ksquare approved these changes

2023-01-05 18:52 UTC, RodrigoLeon-Ksquare approved these changes

2023-01-05 18:54 UTC, merged