Task 19631
Ksquare-University/rc-api pull request #9
Opened 2022-12-29 23:35 UTC by IvannaNouel-Ksquare

2023-01-03 19:56 UTC, GabrielOsorno-Ksquare requested changes

2023-01-03 19:56 UTC, GabrielOsorno-Ksquare commented on src/models/Manager.Model.ts
> +    sequelize
I think we should all add tableName, so all the table names are standardized at snake_case

2023-01-03 19:56 UTC, GabrielOsorno-Ksquare commented on src/models/Manager.Model.ts
> +        restaurant_id: {
It might be great if you use allowNull on restaurant_id.

2023-01-04 17:13 UTC, YumilRuedaFlores-Ksquare approved these changes

2023-01-04 19:18 UTC, BrandonHernandez-Ksquare approved these changes

2023-01-04 20:03 UTC, GabrielOsorno-Ksquare submitted a review, later dismissed

2023-01-05 19:39 UTC, ClaudiaDiaz-Ksquare approved these changes

2023-01-05 19:40 UTC, merged